# Generated by Django 3.2.19 on 2023-11-21 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=100, null=True)),
                ('term', models.CharField(max_length=100, null=True)),
                ('parent', models.CharField(max_length=100, null=True)),
                ('fieldName', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_api_link', models.URLField()),
                ('metadata_api_link', models.URLField()),
                ('data_api_header', models.TextField()),
                ('metadata_api_header', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MappedApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('my_json_object', models.TextField()),
                ('dcat_ttl', models.TextField()),
                ('dcat_jsonld', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.ManyToManyField(to='modelos.CustomField')),
                ('fieldMappingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mapping', to='modelos.fieldmapping')),
            ],
        ),
    ]
