# Generated by Django 3.2.19 on 2023-09-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappedapi',
            old_name='mappedApiID',
            new_name='fieldMappingID',
        ),
    ]
